name: pomo_app
description: "Pomodoro Timer"
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  window_manager: ^0.3.9
  drift: ^2.18.0
  path_provider: ^2.0.0
  path: ^1.9.0
  provider: ^6.1.2
  fl_chart: ^0.68.0
  local_notifier: ^0.1.6
  number_text_input_formatter: ^1.0.0+8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.9

flutter:

  uses-material-design: true
  assets:
    - fonts/
